name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Generate docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features --no-deps


      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
